/**
 * ============================================================
 * CARNITAS CARMELITA — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on June 30, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Carnitas Carmelita",
  "tagline": "Authentic Mexican Food",
  "preloaderTagline": "Authentic Mexican Food • Amnicola Hwy",
  "copyrightText": "",
  "logoPrimary": "",
  "logoAlternate": "",
  "logoHeaderChoice": "none",
  "logoHeaderHeight": 40,
  "logoSplashChoice": "none",
  "logoSplashHeight": 80,
  "logoSplashMode": "logo-name-tagline",
  "logoFooterChoice": "none",
  "logoFooterHeight": 40,
  "pageHeaders": {
    "about": {
      "label": "About Us",
      "title": "About Us",
      "subtitle": ""
    },
    "contact": {
      "label": ""
    }
  },
  "attorneyName": "",
  "attorneyDegree": "",
  "attorneyCredentials": [],
  "aboutBio1": "",
  "aboutBio2": "",
  "attorneyPhoto": "",
  "aboutNavLabel": "About Us",
  "attorneys": [
    {
      "name": "",
      "degree": "",
      "education": [],
      "photo": "",
      "credentials": [],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "(423) 201-4841",
  "phoneRaw": "+14232014841",
  "fax": "",
  "email": "",
  "address": "2604 Amnicola Hwy",
  "city": "Chattanooga",
  "state": "Tennessee",
  "stateAbbr": "TN",
  "zip": "37406",
  "locations": [
    {
      "name": "Carnitas Carmelita",
      "phone": "(423) 201-4841",
      "phoneRaw": "+14232014841",
      "fax": "",
      "email": "",
      "address": "2604 Amnicola Hwy",
      "city": "Chattanooga",
      "state": "Tennessee",
      "stateAbbr": "TN",
      "zip": "37406",
      "hours": [
        {
          "days": "Mon - Sat",
          "hours": "10.30am - 3.00pm"
        },
        {
          "days": "Sunday",
          "hours": "Closed"
        }
      ]
    }
  ],
  "hours": [
    {
      "days": "Mon - Sat",
      "hours": "10.30am - 3.00pm"
    },
    {
      "days": "Sunday",
      "hours": "Closed"
    }
  ],
  "socialLinks": [],
  "stats": [],
  "colors": {
    "navy": "#8e1b1b",
    "navyLight": "#8e1b1b",
    "gold": "#ffbf79",
    "goldLight": "#ffa94a",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#f3eee2",
    "chrome": "#8e1b1b"
  },
  "fontColors": {
    "heading": "#400f0f",
    "body": "#545454",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Raleway",
  "fontBody": "Source Sans 3",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "",
    "about": "",
    "contact": "",
    "privacy": ""
  },
  "heroBg": {
    "type": "slideshow",
    "bgColor": "#8e1b1b",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [
      {
        "imagePath": "food/tacos-01.png",
        "position": "center center"
      },
      {
        "imagePath": "food/torta-01.png",
        "position": "center center"
      },
      {
        "imagePath": "food/burrito-01.png",
        "position": "center center"
      }
    ],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 8,
    "overlayColor": "#000000",
    "overlayOpacity": 0.3,
    "videoClips": [],
    "videoFallback": "",
    "videoTransSpeed": 1.2,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Taste of Tradition",
  "heroSubline": "Ven por las mejores carnitas, birria, carne asada y tamales, o disfruta de nuestros tacos, burritos, tortas y quesadillas. ¡Comida de verdad para darte fuerza cada día!\n\n\nStop by for the best carnitas, birria, carne asada, and tamales, or grab our fresh tacos, burritos, tortas, and quesadillas. Real food to fuel your day!",
  "heroTrustBullets": [
    "Located next to Subway on Amnicola Highway"
  ],
  "heroPrimaryLabel": "Menu",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "menu",
  "heroSecondaryLabel": "Our Services",
  "heroSecondaryLinkType": "none",
  "heroSecondaryLinkUrl": "",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "",
  "contactSubline": "",
  "contactFormHeading": "Leave Us A Message",
  "contactFormIntro": "",
  "contactPrivacyNote": "",
  "contactForm": [
    {
      "type": "text",
      "label": "Name or Nickname",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "date",
      "label": "Date",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "stars",
      "label": "Rating",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Review",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "select",
      "label": "Review Category",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": [
        "Experience",
        "Food Quality",
        "Location",
        "Wait Time",
        "Price",
        "Other"
      ]
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [
    {
      "name": "Camden Gonzalez",
      "initials": "CG",
      "stars": "5",
      "text": "I took my family to a nearby Mexican restaurant last weekend, and it was a delightful experience! The menu was extensive, offering a variety of options for everyone. We ordered a mix of tacos, burritos, and nachos, and each dish was bursting with flavor. The highlight was definitely the slow-cooked pork; it was fall-apart tender and seasoned to perfection. The kids even loved their meals, which is always a win in my book! The staff was friendly and attentive, making sure our drinks were always full. My only suggestion would be to add more vegetarian options to the menu, as it was a bit limited for my daughter. Overall, a fantastic family dining experience!",
      "meta": "Restaurants",
      "date": "2025-03-23"
    },
    {
      "name": "Jaxson Laurent",
      "initials": "JL",
      "stars": "5",
      "text": "I recently dined at a local spot and was blown away by the flavors of their carnitas. The meat was incredibly tender and seasoned perfectly. I loved the fresh salsa that accompanied it—such a vibrant kick! The ambiance was cozy and welcoming, making it a great place to unwind after a long day. My only critique would be that the service was a bit slow during peak hours, but the food more than made up for it. I can't wait to return and try more dishes from their menu!",
      "meta": "Meat & Seafood",
      "date": "2025-01-15"
    },
    {
      "name": "Kathleen Armstrong",
      "initials": "KA",
      "stars": "4",
      "text": "Had dinner at this amazing spot last week! The atmosphere was lively, and the decor had a fun, authentic vibe that really set the mood. I ordered the carnitas plate, and it did not disappoint—super juicy and flavorful. The portion size was generous, and I appreciated the fresh toppings that came with it. My only complaint would be the wait time; it took a bit longer than expected for our food to arrive. However, the staff was apologetic and friendly throughout our meal. I will definitely be coming back, especially to try their tacos next time!",
      "meta": "",
      "date": "2024-10-27"
    },
    {
      "name": "Jeff Osborne",
      "initials": "JO",
      "stars": "5",
      "text": "One of the best hidden treasures in Chattanooga! Food is awesome and the staff are very courteous. Burritos, tacos, quesadillas, tortas, stuffed with your choice of about 8 different meat options make for an amazing treat. Included are a fresh cut lime, grilled pepper and a couple of homemade sauces that help kick up the heat and flavor of their authentic delights!",
      "meta": "",
      "date": "2017-05-08"
    },
    {
      "name": "George Armstrong",
      "initials": "GA",
      "stars": "5",
      "text": "Great little place on Amnicola Hwy. Authentic street tacos, and their salsa had some good kick. It's affordable too",
      "meta": "",
      "date": "2025-10-03"
    },
    {
      "name": "Mark Bullock",
      "initials": "MB",
      "stars": "5",
      "text": "Everything on the menu is authentic and excellent. I've used them twice to cater my Cinco parties. Looking forward to making it three times!",
      "meta": "",
      "date": "2023-06-17"
    }
  ],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Location",
  "ctaLinkType": "internal",
  "ctaLinkUrl": "home",
  "navDefaultOpen": false,
  "footerNavDefaultOpen": false,
  "headerAlwaysSolid": false,
  "pageToggles": {
    "about": false,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "testimonials",
      "navLabel": "Testimonials",
      "emoji": "✉️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "hiddenFromMainNav": false,
      "hiddenFromFooterNav": false,
      "sections": [
        {
          "type": "testimonials",
          "label": "",
          "background": "alt",
          "anchorId": "testimonials",
          "heading": "Testimonios (Testimonials)",
          "subtitle": "",
          "showReviews": false,
          "count": 3,
          "showReadAll": true,
          "readAllLabel": "Read All Reviews",
          "primarySource": true,
          "items": [
            {
              "name": "Camden Gonzalez",
              "initials": "CG",
              "stars": "5",
              "text": "I took my family to a nearby Mexican restaurant last weekend, and it was a delightful experience! The menu was extensive, offering a variety of options for everyone. We ordered a mix of tacos, burritos, and nachos, and each dish was bursting with flavor. The highlight was definitely the slow-cooked pork; it was fall-apart tender and seasoned to perfection. The kids even loved their meals, which is always a win in my book! The staff was friendly and attentive, making sure our drinks were always full. My only suggestion would be to add more vegetarian options to the menu, as it was a bit limited for my daughter. Overall, a fantastic family dining experience!",
              "meta": "Restaurants",
              "date": "2025-03-23"
            },
            {
              "name": "Jaxson Laurent",
              "initials": "JL",
              "stars": "5",
              "text": "I recently dined at a local spot and was blown away by the flavors of their carnitas. The meat was incredibly tender and seasoned perfectly. I loved the fresh salsa that accompanied it—such a vibrant kick! The ambiance was cozy and welcoming, making it a great place to unwind after a long day. My only critique would be that the service was a bit slow during peak hours, but the food more than made up for it. I can't wait to return and try more dishes from their menu!",
              "meta": "Meat & Seafood",
              "date": "2025-01-15"
            },
            {
              "name": "Kathleen Armstrong",
              "initials": "KA",
              "stars": "4",
              "text": "Had dinner at this amazing spot last week! The atmosphere was lively, and the decor had a fun, authentic vibe that really set the mood. I ordered the carnitas plate, and it did not disappoint—super juicy and flavorful. The portion size was generous, and I appreciated the fresh toppings that came with it. My only complaint would be the wait time; it took a bit longer than expected for our food to arrive. However, the staff was apologetic and friendly throughout our meal. I will definitely be coming back, especially to try their tacos next time!",
              "meta": "",
              "date": "2024-10-27"
            },
            {
              "name": "Jeff Osborne",
              "initials": "JO",
              "stars": "5",
              "text": "One of the best hidden treasures in Chattanooga! Food is awesome and the staff are very courteous. Burritos, tacos, quesadillas, tortas, stuffed with your choice of about 8 different meat options make for an amazing treat. Included are a fresh cut lime, grilled pepper and a couple of homemade sauces that help kick up the heat and flavor of their authentic delights!",
              "meta": "",
              "date": "2017-05-08"
            },
            {
              "name": "George Armstrong",
              "initials": "GA",
              "stars": "5",
              "text": "Great little place on Amnicola Hwy. Authentic street tacos, and their salsa had some good kick. It's affordable too",
              "meta": "",
              "date": "2025-10-03"
            },
            {
              "name": "Mark Bullock",
              "initials": "MB",
              "stars": "5",
              "text": "Everything on the menu is authentic and excellent. I've used them twice to cater my Cinco parties. Looking forward to making it three times!",
              "meta": "",
              "date": "2023-06-17"
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "internal",
          "primary_linkLabel": "Leave Us A Message",
          "primary_linkUrl": "contact",
          "primary_anchorId": "",
          "secondary_linkType": "none",
          "secondary_linkLabel": "",
          "secondary_linkUrl": "",
          "secondary_anchorId": ""
        }
      ]
    },
    {
      "slug": "menu",
      "navLabel": "Menu",
      "emoji": "🧾",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "hiddenFromMainNav": false,
      "hiddenFromFooterNav": false,
      "sections": [
        {
          "type": "rotating-cards",
          "label": "",
          "background": "alt",
          "anchorId": "menu",
          "heading": "Main Menu",
          "subtitle": "",
          "visibleCards": 3,
          "cardHeight": 420,
          "showDots": true,
          "showArrows": true,
          "showPeek": false,
          "autoplay": true,
          "autoplaySpeed": 4,
          "items": [
            {
              "title": "",
              "body": "Michoacan Style",
              "imagePath": "food/tacos-02.png",
              "bgColor": "",
              "fullBleed": true,
              "zoomEnabled": false,
              "textColor": "light",
              "btnLabel": "Al Estilo Michoacan",
              "btnLinkType": "internal",
              "btnLinkUrl": "menu",
              "btnAnchorId": "menu-michoacan"
            },
            {
              "title": "",
              "body": "Specialties",
              "imagePath": "food/plate-burrito.png",
              "bgColor": "",
              "fullBleed": true,
              "zoomEnabled": false,
              "textColor": "light",
              "btnLabel": "Especialidades",
              "btnLinkType": "internal",
              "btnLinkUrl": "menu",
              "btnAnchorId": "menu-specialties"
            },
            {
              "title": "",
              "body": "Sides",
              "imagePath": "",
              "bgColor": "",
              "fullBleed": true,
              "zoomEnabled": false,
              "textColor": "light",
              "btnLabel": "Guarniciones",
              "btnLinkType": "internal",
              "btnLinkUrl": "menu",
              "btnAnchorId": "menu-sides"
            },
            {
              "title": "",
              "body": "Beverages",
              "imagePath": "",
              "bgColor": "",
              "fullBleed": true,
              "zoomEnabled": false,
              "textColor": "light",
              "btnLabel": "Beverajes",
              "btnLinkType": "internal",
              "btnLinkUrl": "menu",
              "btnAnchorId": "menu-beverages"
            }
          ]
        },
        {
          "type": "pricing",
          "label": "",
          "background": "light",
          "anchorId": "menu-michoacan",
          "heading": "Al Estilo Michoacan (Michoacan Style)",
          "subtitle": "Meat Choices\n• Carnitas (Fried Pork)\n• Birria (Beef Braised)\n• Carne Asada (Grill Steak)\n• Chorizo (Mexican Sausage)\n• Pollo (Chicken)\n• Al pastor (Marinated Pork)\n\nSpecial Meat Choices\n• Lengua (Beef Tongue) - Add $1.75\n• Buche (Pig Crop)\n• Tripa (Intestines) - Add $0.75\n• Pescado (Fish) - Add $0.75\n• Camaron (Shrimp) - Add $0.75\n\nAll your orders are served with a side of Lime, Salsa verde, Salsa roja and a grilled Jalapeño.\n\nSalsas are served on side.",
          "maxCols": 2,
          "colFullWidth": false,
          "items": [
            {
              "name": "Tortas",
              "tagline": "Large Grilled Mexican Sandwich Layered With Lettuce, Tomato, Onions, Jalapeno, Avocado, Queso and your Choice of Meat",
              "price": "$7.00",
              "period": "/ choice of meat",
              "icon": "",
              "imagePath": "food/torta-01.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Special Meat Choices",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "• Lengua (Beef Tongue) - $8.75\n• Tripa (Intestines) - $7.75\n• Pescado (Fish) - $7.75\n• Camaron (Shrimp) - $7.75",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Quesadilla",
              "tagline": "Flour tortilla with cheese and your choice of meat.",
              "price": "$7.50",
              "period": "/ choice of meat",
              "icon": "",
              "imagePath": "food/quesadilla -01.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Special Meat Choices",
                  "status": "",
                  "isGroup": true
                },
                {
                  "label": "• Lengua (Beef Tongue) - $9.25\n• Tripa (Intestines) - $8.25\n• Pescado (Fish) - $8.25\n• Camaron (Shrimp) - $8.25",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Burrito",
              "tagline": "Flour tortilla wrapped with beans, rice, pico de gallo, cheese, and your choice of meat.",
              "price": "$7.00",
              "period": "/ choice of meat",
              "icon": "🌯",
              "imagePath": "food/burrito-01.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Special Meat Choices",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "• Lengua (Beef Tongue) - $8.75\n• Tripa (Intestines) - $7.75\n• Pescado (Fish) - $7.75\n• Camaron (Shrimp) - $7.75",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Tacos",
              "tagline": "Served on Corn Tortilla with Cilantro, Onions, and your Choice of Meat",
              "price": "$3.00",
              "period": "/ choice of meat",
              "icon": "",
              "imagePath": "food/tacos-01.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": [
                {
                  "label": "Special Meat Choices",
                  "status": "",
                  "isGroup": false
                },
                {
                  "label": "• Lengua (Beef Tongue) - $4.50\n• Tripa (Intestines) - $3.75\n• Pescado (Fish) - $3.75\n• Camaron (Shrimp) - $3.75",
                  "status": "",
                  "isGroup": false
                }
              ]
            },
            {
              "name": "Tamales",
              "tagline": "",
              "price": "$2.75",
              "period": "/ Carnitas (Pork) or Pollo (Chicken)",
              "icon": "",
              "imagePath": "food/tamales.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            }
          ]
        },
        {
          "type": "pricing",
          "label": "",
          "background": "dark",
          "anchorId": "menu-specialties",
          "heading": "Especialidades (Specialties)",
          "subtitle": "",
          "maxCols": 2,
          "colFullWidth": false,
          "items": [
            {
              "name": "Carnitas",
              "tagline": "Fried pork served with rice, beans and tortilla (flour or corn)",
              "price": "$12.50",
              "period": "",
              "icon": "",
              "imagePath": "food/torta-01.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Carne Azada",
              "tagline": "Thinly sliced Steak grilled with Onions served with Rice, Beans and Tortillas (flour or corn)",
              "price": "$10.50",
              "period": "",
              "icon": "",
              "imagePath": "food/special-carne-azada.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Birria",
              "tagline": "Beef braised served with Rice, Beans and Tortilla (flour or corn)",
              "price": "$10.50",
              "period": "",
              "icon": "",
              "imagePath": "food/burrito-01.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            },
            {
              "name": "Pechuga de Pollo Ala Parila",
              "tagline": "Grilled chicken with Grilled Onion Served with Rice, Beans and Tortilla (flour or corn)",
              "price": "$10.00",
              "period": "",
              "icon": "",
              "imagePath": "food/tacos-01.png",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "light",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            }
          ]
        },
        {
          "type": "bullets",
          "label": "",
          "background": "alt",
          "anchorId": "menu-sides",
          "heading": "Guarniciones (Sides)",
          "subtitle": "",
          "fullWidth": false,
          "items": [
            {
              "icon": "🥑",
              "title": "Guacamole - $2.50",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "icon": "🍛",
              "title": "Rice and Beans - $2.00",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "icon": "🇲🇽",
              "title": "Pico de gallo - $1.50",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "icon": "🥗",
              "title": "Side Salad - $2.00",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "icon": "🐄",
              "title": "Sour Cream - $1.00",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            }
          ]
        },
        {
          "type": "bullets",
          "label": "",
          "background": "light",
          "anchorId": "menu-beverages",
          "heading": "Beverajes (Beverages)",
          "subtitle": "",
          "fullWidth": false,
          "items": [
            {
              "icon": "🇲🇽",
              "title": "Mexican Drinks - $1.75",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "icon": "🍶",
              "title": "Bottle Drinks - $1.50",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "icon": "🥫",
              "title": "Can Drink - $1.00",
              "desc": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Our Location",
          "secondary_linkUrl": "home",
          "secondary_anchorId": "locations"
        }
      ]
    },
    {
      "slug": "homies-shop",
      "navLabel": "Homies Shop",
      "emoji": "🤡",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "hiddenFromMainNav": false,
      "hiddenFromFooterNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "",
          "background": "dark",
          "anchorId": "homies-intro",
          "heading": "Compra el Bloque (Shop the Block)",
          "body": "Coleccionables auténticos de Homies:\nLleva la esencia del barrio a tu hogar. Creados en 1994 por el legendario artista chicano David Gonzales, los Homies evolucionaron de una tira cómica de la revista Lowrider a un fenómeno global de la cultura urbana. Ahora, es tu turno de crear tu propio barrio. Cada personaje tiene su propio estilo, historia y actitud únicos. ¡Explora nuestra colección hoy mismo y añade un pedazo de la legendaria historia urbana a tu estantería!\n\nAuthentic Homies Collectibles:\nBring the ultimate neighborhood home. First created in 1994 by legendary Chicano artist David Gonzales, Homies evolved from a Lowrider magazine comic strip into a global street-culture phenomenon. Now, it is your turn to build your block. Each character brings its own unique style, story, and attitude. Explore our collection today and add some legendary urban history to your display shelf!",
          "imagePath": "homies/homies-group.png",
          "imagePosition": "left",
          "imageMaxWidth": "380",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "rotating-cards",
          "label": "",
          "background": "dark",
          "anchorId": "homies-cards",
          "heading": "Comprar Coleccionables (Shop Collectables)",
          "subtitle": "",
          "visibleCards": 3,
          "cardHeight": 300,
          "showDots": true,
          "showArrows": true,
          "showPeek": false,
          "autoplay": false,
          "autoplaySpeed": 4,
          "items": [
            {
              "title": "Posters",
              "body": "",
              "imagePath": "homies/homies-poster-01.jpeg",
              "bgColor": "",
              "fullBleed": true,
              "zoomEnabled": false,
              "textColor": "light",
              "btnLabel": "Pósters",
              "btnLinkType": "internal",
              "btnLinkUrl": "homies-shop",
              "btnAnchorId": "homies-posters"
            },
            {
              "title": "Figurines",
              "body": "",
              "imagePath": "homies/homies-og.webp",
              "bgColor": "",
              "fullBleed": true,
              "zoomEnabled": false,
              "textColor": "light",
              "btnLabel": "Figuritas",
              "btnLinkType": "internal",
              "btnLinkUrl": "homies-shop",
              "btnAnchorId": "homies-figurines"
            },
            {
              "title": "Key Chains",
              "body": "",
              "imagePath": "homies/homies-kc-latina-01.webp",
              "bgColor": "",
              "fullBleed": true,
              "zoomEnabled": false,
              "textColor": "light",
              "btnLabel": "Llaveros",
              "btnLinkType": "internal",
              "btnLinkUrl": "homies-shop",
              "btnAnchorId": "homies-key-chains"
            }
          ]
        },
        {
          "type": "pricing",
          "label": "",
          "background": "light",
          "anchorId": "homies-posters",
          "heading": "Pósters (Posters)",
          "subtitle": "",
          "maxCols": 2,
          "colFullWidth": false,
          "items": [
            {
              "name": "Homies Poster",
              "tagline": "Adquiera una pieza de la historia de la cultura pop chicana. Este enorme diseño clásico de 24x36 pulgadas sirve como la guía visual definitiva, nombrando y detallando meticulosamente las primeras generaciones del icónico universo de figuras de máquinas expendedoras.\n\nOwn a piece of chicano pop-culture history. This massive 24x36-inch classic layout serves as the ultimate visual roadmap, meticulously naming and detailing the early generations of the iconic vending machine figurine universe.",
              "price": "$20",
              "period": "/ US Dollars",
              "icon": "",
              "imagePath": "homies/homies-poster-01.jpeg",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            }
          ]
        },
        {
          "type": "pricing",
          "label": "",
          "background": "alt",
          "anchorId": "homies-figurines",
          "heading": "Figuritas (Figurines)",
          "subtitle": "",
          "maxCols": 2,
          "colFullWidth": false,
          "items": [
            {
              "name": "Big Headz - Clown Prince",
              "tagline": "Adquiera una pieza de la historia de la cultura pop chicana. Este enorme diseño clásico de 24x36 pulgadas sirve como la guía visual definitiva, nombrando y detallando meticulosamente las primeras generaciones del icónico universo de figuras de máquinas expendedoras.\n\nOwn a piece of chicano pop-culture history. This massive 24x36-inch classic layout serves as the ultimate visual roadmap, meticulously naming and detailing the early generations of the iconic vending machine figurine universe.",
              "price": "$99",
              "period": "/ US Dollars",
              "icon": "",
              "imagePath": "homies/homies-og.webp",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            }
          ]
        },
        {
          "type": "pricing",
          "label": "",
          "background": "light",
          "anchorId": "homies-key-chains",
          "heading": "Llaveross (Key Chains)",
          "subtitle": "",
          "maxCols": 2,
          "colFullWidth": false,
          "items": [
            {
              "name": "Latina Charm Key Chain",
              "tagline": "Adquiera una pieza de la historia de la cultura pop chicana. Este enorme diseño clásico de 24x36 pulgadas sirve como la guía visual definitiva, nombrando y detallando meticulosamente las primeras generaciones del icónico universo de figuras de máquinas expendedoras.\n\nOwn a piece of chicano pop-culture history. This massive 24x36-inch classic layout serves as the ultimate visual roadmap, meticulously naming and detailing the early generations of the iconic vending machine figurine universe.",
              "price": "$19",
              "period": "/ US Dollars",
              "icon": "",
              "imagePath": "homies/homies-kc-latina-01.webp",
              "imageSize": "sq",
              "ribbon": "",
              "note": "",
              "cardStyle": "dark",
              "featured": true,
              "cta_linkLabel": "",
              "cta_linkType": "none",
              "cta_linkUrl": "home",
              "cta_anchorId": "",
              "features": []
            }
          ]
        }
      ]
    }
  ],
  "aboutSections": [],
  "homeSections": [
    {
      "type": "testimonials",
      "label": "",
      "background": "light",
      "anchorId": "what-customers-are-saying",
      "heading": "Customer Experiences",
      "subtitle": "",
      "items": [],
      "showReviews": true,
      "count": 3,
      "showReadAll": true,
      "readAllLabel": "Read All Reviews",
      "primarySource": false
    },
    {
      "type": "locations",
      "label": "",
      "background": "light",
      "anchorId": "locations",
      "items": [
        {
          "locationIndex": "0",
          "imagePath": "images/cc-01.png"
        }
      ],
      "displayMode": "feature",
      "layoutMode": "top",
      "featureSide": "left",
      "mapMode": "linkout",
      "maxCols": 2,
      "showHours": true
    }
  ],
  "mapsApiKey": "",
  "footerBio": "",
  "animateStats": false,
  "contactSubmitLabel": "Submit",
  "contactSuccessMsg": "",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public",
    "cp-0": "public",
    "cp-1": "public",
    "cp-2": "public"
  },
  "fontDisplayCustom": "",
  "fontBodyCustom": "",
  "_savedAt": 1782825362419,
  "heroPrimaryAnchorId": "",
  "heroSecondaryAnchorId": "",
  "ctaAnchorId": "locations"
};
